In [1]:
# Two Dimensional Numpy

In [2]:
# 1. Basics and Array Creation in 2D
# 2. Indexing and Slicing in 2D
# 3. Basic Operations in 2D

In [8]:
# Creating a 2D array 
import numpy as np
a = [[1,2,3], [8,9,0]]
A = np.array(a)
A

array([[1, 2, 3],
       [8, 9, 0]])

In [12]:
# we can see the number of dimensions or number of nested lists(we only have two dimensions here, columns and rows)
A.ndim

2

In [14]:
# we can as well see the number of nested lists and number of elements in each list (№ of rows and col)
A.shape

(2, 3)

In [15]:
# we can see the overall number of the elements in an array 
A.size

6

In [19]:
# we can access the elements of an array as follows:
print(A[0][1]) # first number is the number of a row and the second id the number of a column
print(A[0,1])

2
2


In [26]:
# slicing 
B = A[0,0:2]
print(B)
C = A[0:2, 1:3]
print(C)

[1 2]
[[2 3]
 [9 0]]


In [37]:
# add the matrices
x = np.array([[2,3],[6,0]])
y = np.array([[0,3],[2,4]])
z = x+y
print(f'{x} \n plus \n {y} \n is equal to \n {z}')

[[2 3]
 [6 0]] 
 plus 
 [[0 3]
 [2 4]] 
 is equal to 
 [[2 6]
 [8 4]]


In [39]:
# we can mulyiply an array by a scalar
Y = 2*y
Y

array([[0, 6],
       [4, 8]])

In [40]:
# default multiplication of the arrays is performed as follows
s = np.array([[5,2], [6,0]])
n = np.array([[1,3], [2,10]])
s*n
# each element is multiplied by the other corresponding element in the other matrix

array([[ 5,  6],
       [12,  0]])

In [41]:
# to get the result of a conventional matrix multiplication we should use the following function:
np.dot(s,n) #reminder: to multiply the matrices one should have the same number of columns in the 
# first matrix and rows in the second matrix

array([[ 9, 35],
       [ 6, 18]])

In [45]:
# Example: col(t) = rows(y)
t = np.array([[3,4,0], [0,0,1], [2,0,7]])
y = np.array([[5,6], [0,2], [3,1]])
np.dot(t,y)

array([[15, 26],
       [ 3,  1],
       [31, 19]])

In [46]:
# Example: col(t) = rows(y)
t = np.array([3,4,0])
y = np.array([[5,6], [0,2], [3,1]])
np.dot(t,y)

array([15, 26])

In [47]:
# Example: col(t) > rows(y)
t = np.array([[3,4,0,9], [5,8,0,1]])
y = np.array([[5,6], [0,2], [3,1]])
np.dot(t,y)
# the error is shown:

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)